image: b3m33hro/labs:latest
ports:
- port: 6080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: vnc && start-vnc-session.sh
